# Generated by Django 5.1.2 on 2025-09-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_text', models.TextField(verbose_name='Название похода')),
                ('hike_date', models.DateField(verbose_name='Дата похода')),
                ('hike_type', models.CharField(max_length=255, verbose_name='Тип похода')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, verbose_name='id_платежа')),
                ('bank', models.CharField(max_length=255, verbose_name='Банк')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('discount_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id_скидки')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма скидки')),
                ('source_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда пришел клиент')),
                ('tick_status', models.BooleanField(verbose_name='Статус галочки')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tourism.hike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tourism.registereduser')),
            ],
        ),
    ]
