# Generated by Django 5.1.2 on 2025-12-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours_registrations', '0002_add_participant_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourregistration',
            options={'verbose_name': 'Регистрация на тур', 'verbose_name_plural': 'Регистрации на туры'},
        ),
    ]
