# Generated by Django 5.1.2 on 2025-11-15 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Введите номер в формате: 9001234567 (10 цифр без пробелов и символов)', regex='^\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
