# Generated by Django 5.1.2 on 2025-12-28 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания кода'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(choices=[('+7', 'Россия (+7)'), ('+1', 'USA/Canada (+1)'), ('+44', 'UK (+44)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+34', 'Spain (+34)'), ('+31', 'Netherlands (+31)'), ('+43', 'Austria (+43)'), ('+41', 'Switzerland (+41)'), ('+32', 'Belgium (+32)'), ('+46', 'Sweden (+46)'), ('+47', 'Norway (+47)'), ('+45', 'Denmark (+45)'), ('+358', 'Finland (+358)'), ('+48', 'Poland (+48)'), ('+420', 'Czech Republic (+420)'), ('+36', 'Hungary (+36)'), ('+40', 'Romania (+40)'), ('+30', 'Greece (+30)'), ('+90', 'Turkey (+90)')], default='+7', max_length=4, verbose_name='Код страны'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Введите номер телефона (10-15 цифр без пробелов)', regex='^\\d{10,15}$')], verbose_name='Номер телефона'),
        ),
    ]
