# Generated by Django 5.1.2 on 2025-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название похода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание похода')),
                ('start_date', models.DateField(verbose_name='Дата начала похода')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания похода')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('type', models.CharField(max_length=255, verbose_name='Тип похода')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
