# Generated by Django 5.1.2 on 2025-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='min_age',
            field=models.IntegerField(default=0, help_text='0 = нет ограничений', verbose_name='Минимальный возраст'),
        ),
    ]
