# Generated by Django 5.1.2 on 2025-12-28 16:13

from django.db import migrations


def assign_tour_images(apps, schema_editor):
    """Присвоить изображения существующим маршрутам"""
    Tour = apps.get_model('tours', 'Tour')

    # Маппинг ID маршрутов на изображения
    tour_images = {
        1: 'tours/stolbyonback.jpg',  # Красноярские столбы
        2: 'tours/elbrus.jpg',  # Эльбрус
        3: 'tours/mana.jpg',  # Манский порог
        4: 'tours/ribnaya.png',  # Музыкальное озеро
    }

    # Дефолтные изображения по типам
    default_images = {
        'Пеший туризм': 'tours/peshiy.png',
        'Горный туризм': 'tours/mountain_main.png',
        'Водный туризм': 'tours/vodniy.png',
    }

    # Присваиваем изображения
    for tour in Tour.objects.all():
        if tour.id in tour_images:
            tour.image = tour_images[tour.id]
        elif tour.type in default_images:
            tour.image = default_images[tour.type]
        else:
            # Fallback для неизвестных типов
            tour.image = 'tours/peshiy.png'

        tour.save()


def reverse_assign_tour_images(apps, schema_editor):
    """Отменить присвоение изображений"""
    Tour = apps.get_model('tours', 'Tour')
    Tour.objects.all().update(image='')


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_min_age'),
    ]

    operations = [
        migrations.RunPython(assign_tour_images, reverse_assign_tour_images),
    ]

