# Generated by Django 5.1.2 on 2025-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_add_tour_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность похода'),
        ),
    ]
