# Generated by Django 5.1.2 on 2025-12-28 23:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание похода'),
        ),
    ]
